CMS_CORE_NG/Areas/Admin/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Areas/Admin/Controllers/EmailSettingsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EmailSettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Areas/Admin/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Areas/Admin/Controllers/SiteSettingsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SiteSettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Areas/Admin/Controllers/UserRoleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserRoleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Controllers/WeatherForecastController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}

CMS_CORE_NG/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CMS_CORE_NG.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CMS_CORE_NG/Areas/Admin/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Admin Home"; }

CMS_CORE_NG/Areas/Admin/Views/Shared/_AdminBlankLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="Welcome to the Super Admin Panel of Car Dealer" />
    <meta name="author" content="Techhowdy" />
    <!-- Favicon icon -->
    <link href="~/favicon.ico" rel="icon" />
    <environment include="Development">
        <!-- Custom CSS -->
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/custom/css/admin/login.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
        <!-- Font Awesome J -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    </environment>
    <environment exclude="Development">
        <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/custom/css/admin/login.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>

    <!-- ============================================================== -->
    <!-- Main wrapper -->
    <!-- ============================================================== -->
    <div class="wrapper">

        <div class="container-fluid bg-white shadow">

            @RenderBody()

        </div>
        <footer class="container-fluid fixed-bottom">
            <div class="copyright text-center my-auto">
                <span> Admin Panel Created By <a href="https://techhowdy.com">Techhowdy<sup>&copy;</sup>2019</a></span>
            </div>
        </footer>

    </div>


    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <!-- Bootstrap tether Core JavaScript -->
        <script src="~/lib/popper.js/umd/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <!-- Custom JS -->
        <script src="~/lib/custom/js/admin/admin.js"></script>


    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/custom/js/admin/admin.min.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>

</html>

CMS_CORE_NG/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@*@model ModelService.AdminBaseViewModel*@
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>ADMIN | Home Page</title>
    <meta name="description" content="Cms Application Buils with Asp.net Core 3.0 and Angular 10" />
    <meta name="author" content="Techhowdy" />
    <!-- Favicon icon -->
    <link href="~/favicon.ico" rel="icon" />
    @await Html.PartialAsync("_ApplicationHeaderStylesPartial")
    @RenderSection("Styles", required: false)
</head>
<body>

    <!-- ============================================================== -->
    <!-- Main wrapper -->
    <!-- ============================================================== -->
    <div class="wrapper">
      @await Html.PartialAsync("_SidebarLayout")
        <div id="content">
            @await Html.PartialAsync("_TopbarLayout")
     @*       @await Html.PartialAsync("_StatsLayout")*@
            @RenderBody()
        </div>
    </div>
    @await Html.PartialAsync("_FooterLayout")
    @await Html.PartialAsync("_UIScriptsPartial")
    @RenderSection("Scripts", required: false)
</body>
</html>

CMS_CORE_NG/Areas/Admin/Views/Shared/_ApplicationHeaderStylesPartial.cshtml
<environment include="Development">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/custom/css/admin/admin.css" rel="stylesheet" />
</environment>
<environment exclude="Development">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/custom/css/admin/admin.min.css" rel="stylesheet" />
</environment>

CMS_CORE_NG/Areas/Admin/Views/Shared/_FooterLayout.cshtml
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            @* <span>@Html.Raw(@Model.SiteWideSetting.WebsiteFooter)</span>*@
            <span>sabriiiiiine</span>
        </div>
    </div>
</footer>

CMS_CORE_NG/Areas/Admin/Views/Shared/_SidebarLayout.cshtml
<!-- Sidebar  -->
<nav id="sidebar" class="navbar-light bg-white topbar mb-4 static-top shadow">
    <div class="sidebar-header bg-white">
        <a asp-controller="Home" asp-action="Index">
            <h3 class="brand">Techhowdy<sup>.com</sup></h3>
            <strong class="brand">TH</strong>
        </a>
    </div>


    <ul class="list-unstyled components">
        <li>
            <a asp-controller="Home" asp-action="Index">
                <i class="fas fa-home"></i>
                Home
            </a>
        </li>
        <li>
            <a href="#userSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <i class="far fa-user"></i>
                Users
            </a>
            <ul class="collapse list-unstyled" id="userSubmenu">
                <div class="innerList">
                    <li>
                        <a asp-action="Index" asp-area="Admin" asp-controller="User">All Users</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-area="Admin" asp-controller="UserRole">User Roles</a>
                    </li>
                </div>
            </ul>
        </li>
        <li>
            <a href="#settingsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                <i class="fas fa-cogs"></i>
                Settings
            </a>
            <ul class="collapse list-unstyled" id="settingsSubmenu">
                <div class="innerList">
                    <li>
                        <a asp-action="Index" asp-area="Admin" asp-controller="SiteSettings">Site Settings</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-area="Admin" asp-controller="EmailSettings">Email Settings</a>
                    </li>
                </div>
            </ul>
        </li>
    </ul>
</nav>

CMS_CORE_NG/Areas/Admin/Views/Shared/_TopbarLayout.cshtml
@*@model ModelService.AdminBaseViewModel*@
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top">
<!-- Sidebar Toggle (Topbar) -->
<button type="button" id="sidebarCollapse" class="btn btn-link rounded-circle mr-3">
    <i class="fas fa-bars"></i>
</button>
<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           @* <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Model.Profile.Firstname @Model.Profile.Lastname</span>*@
           @* <img class="img-profile rounded-circle" src="@Model.Profile.ProfilePic">*@
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            <a class="dropdown-item" asp-area="Admin" asp-controller="Profile" asp-action="Index" method="get">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
            </a>
            <a class="dropdown-item" asp-controller="Profile" asp-action="Security" method="get">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Security
            </a>
            <a class="dropdown-item" asp-controller="Profile" asp-action="Activity" method="get">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
            </a>
            <div class="dropdown-divider"></div>
            <form asp-area="Admin" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm">
                <button class="dropdown-item" href="#" data-toggle="modal" type="submit">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </button>
            </form>
        </div>
    </li>

</ul>
</nav>

CMS_CORE_NG/Areas/Admin/Views/Shared/_UIScriptsPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/lib/popper.js/umd/popper.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/custom/js/admin/admin.js"></script>
    <!-- Custom JS -->
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/lib/popper.js/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <!-- Custom JS -->
    <script src="~/lib/custom/js/admin/admin.min.js"></script>
</environment>